name: SonarCloud

on:
  push:
    branches:
      - main

jobs:
  sonar:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Run Tests and Generate Coverage
        run: |
          # Crea directorio necesario para el backend y ajusta permisos
          sudo mkdir -p /app/uploads
          sudo chown -R $USER:$USER /app

          # Instalación de dependencias del API
          pip install -r apps/api/requirements.txt
          
          # Configura el path para que Python encuentre tus módulos y paquetes
          export PYTHONPATH=$PYTHONPATH:$(pwd)/apps/api:$(pwd)
          
          # Ejecuta los tests generando el reporte XML para Sonar
          pytest apps/api/tests/ \
            --cov=apps/api/app \
            --cov=packages \
            --cov-report=xml:coverage.xml \
            --cov-report=term

      - name: SonarCloud Scan
        uses: SonarSource/sonarqube-scan-action@fd88b7d7ccbaefd23d8f36f73b59db7a3d246602 # v6.0.0
        with:
          args: >
            "-Dsonar.projectKey=Moises-Mestas_All-In-One2"
            "-Dsonar.organization=moises-mestas"
            "-Dsonar.python.coverage.reportPaths=coverage.xml"
            "-Dsonar.sources=apps/api/app,packages"
            "-Dsonar.tests=apps/api/tests"
            "-Dsonar.exclusions=apps/api/tests/**,**/.pytest_cache/**"
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}